# from
FROM python:3.12-slim
LABEL maintainer="Jamie Seol <theeluwin@gmail.com>"

# prepare
RUN mkdir -p /src
RUN mkdir -p /dist
WORKDIR /src

# install packages
COPY requirements.txt .
RUN pip install -r requirements.txt

# run
EXPOSE 8000
CMD ["./entrypoint.dev.sh"]
