# from
FROM python:3.12-slim
LABEL maintainer="Jamie Seol <theeluwin@gmail.com>"

# envs
ENV DEBUG=1

# prepare
RUN mkdir -p /src
RUN mkdir -p /dist
WORKDIR /src

# install packages
COPY requirements.txt .
RUN pip install -r requirements.txt

# run
EXPOSE 8000
CMD ["pelican", "-o", "/dist", "-s", "pelicanconf.py", "--autoreload", "--listen", "--bind", "0.0.0.0", "--port", "8000", "content"]
